/** @format */

const shop = [
  {
    id: 0,
    category: "Men Clothing",
    type: "Top",
    brand: "Dior",
    color: "blue",
    size: "medium",
    price: 349.99,
    image: "img/top_1_front.png",
  },
  {
    id: 1,
    category: "Men Clothing",
    type: "Top",
    brand: "Dior",
    color: "Brown",
    size: "medium",
    price: 349.99,
    image: "img/top_1_front.png",
  },
  {
    id: 2,
    category: "Men Clothing",
    type: "Top",
    brand: "Dior",
    color: "blue",
    size: "medium",
    price: 349.99,
    image: "img/top_1_front.png",
  },
  {
    id: 3,
    category: "Men Clothing",
    type: "Top",
    brand: "Dior",
    color: "blue",
    size: "medium",
    price: 349.99,
    image: "img/top_1_front.png",
  },
  {
    id: 4,
    category: "Men Clothing",
    type: "Top",
    brand: "Dior",
    color: "blue",
    size: "medium",
    price: 349.99,
    image: "img/top_1_front.png",
  },
  {
    id: 5,
    category: "Men Clothing",
    type: "Top",
    brand: "Dior",
    color: "blue",
    size: "medium",
    price: 349.99,
    image: "img/top_1_front.png",
  },
  {
    id: 6,
    category: "Men Clothing",
    type: "Top",
    brand: "Dior",
    color: "blue",
    size: "medium",
    price: 349.99,
    image: "img/top_1_front.png",
  },
];

module.exports = { shop };
